### ISSUE TITLE
MYSQL ERROR

### ISSUE THREAD

**Issue by luggz** [ESX-Org/esx_policejob#221]
[ERROR] [MySQL] [esx_policejob] An error happens on MySQL for query "[object Obj
ect]": ER_BAD_FIELD_ERROR: Unknown column 'type' in 'field list'
Error: (node:6772) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTI
ON]: unexpected PromiseRejectEvent
    at process.<anonymous> (internal/process/promises.js:27:25)
    at <anonymous>
    at Query.db.query [as _callback] (mysql-async.js:4973:13)
    at Query.Sequence.end (mysql-async.js:280:24)
    at Query.ErrorPacket (mysql-async.js:2122:8)
    at Protocol._parsePacket (mysql-async.js:5941:23)
    at Parser.write (mysql-async.js:6198:12)
    at Protocol.write (mysql-async.js:5701:16)
    at Socket.<anonymous> (mysql-async.js:693:28)
    at emitOne (events.js:116:13)
Error: (node:6772) UnhandledPromiseRejectionWarning: Unhandled promise rejection
. This error originated either by throwing inside of an async function without a
 catch block, or by rejecting a promise which was not handled with .catch(). (re
jection id: 1)
Error: (node:6772) [DEP0018] DeprecationWarning: Unhandled promise rejections ar
e deprecated. In the future, promise rejections that are not handled will termin
ate the Node.js process with a non-zero exit code.
Error: (node:6772) UnhandledPromiseRejectionWarning: Error: ER_BAD_FIELD_ERROR:
Unknown column 'type' in 'field list'
    at Query.Sequence._packetToError (mysql-async.js:244:14)
    at Query.ErrorPacket (mysql-async.js:2109:18)
    at Protocol._parsePacket (mysql-async.js:5941:23)
    at Parser.write (mysql-async.js:6198:12)
    at Protocol.write (mysql-async.js:5701:16)
    at Socket.<anonymous> (mysql-async.js:693:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (mysql-async.js:4728:23)
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at Object.global.exports [as callback] (mysql-async.js:4985:5)
    at citizen:/scripting/v8/main.js:87:41
Error: (node:6772) UnhandledPromiseRejectionWarning: Unhandled promise rejection
. This error originated either by throwing inside of an async function without a
 catch block, or by rejecting a promise which was not handled with .catch(). (re
jection id: 2)

**Comment by Bazookan** [comment]
Getting the same error.

**Comment by luggz** [comment]
Did you install the esx_vehicleshop updated script and the sql file?

**Comment by Bazookan** [comment]
No, just updated esx_policejob. Nothing else

**Comment by luggz** [comment]
fixed by dding a , on line 46 after '0',

CREATE TABLE `owned_vehicles` (
	`owner` varchar(22) NOT NULL,
	`plate` varchar(12) NOT NULL,
	`vehicle` longtext,
	`type` VARCHAR(20) NOT NULL DEFAULT 'car',
	`job` VARCHAR(20) NOT NULL,
	`stored` TINYINT(1) NOT NULL DEFAULT '0',   <--------HERE

	PRIMARY KEY (`plate`)
);
