### ISSUE TITLE
Error code at setting job

### ISSUE THREAD

**Issue by Er1cx** [ESX-Org/esx_policejob#296]
Hi i have error code, when i writing in console setjob police, i have no idea how to fix it, someone can help? :/ 

Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: @es_extended/server/classes/player.lua:354: attempt to index a nil value (field '?')
stack traceback:
        @es_extended/server/classes/player.lua:354: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:20
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)

**Comment by gabew18** [comment]
/setjob 1 police 4 

1 is the user id of the player

police is well the job

4 is the level, 4 for police = chief

if that dosent work, make sure u imported all ur sqls
